name: baixa_tube
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.8.1
  youtube_explode_dart: ^2.3.10
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  just_audio_windows: ^0.2.2
  just_audio: ^0.9.46
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  path: ^1.9.0
  ffmpeg_helper: ^1.0.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/icons/

flutter_launcher_icons:
  file: "assets/icons/baixa_tube_logo.png"
  windows:
    generate: true
    image_path: "assets/icons/baixa_tube_logo.png"
    icon_size: 48 